services:
  # Configuration du service backend
  - type: web
    name: smart-parking-api
    runtime: docker
    dockerfilePath: ./Dockerfile.backend
    plan: free
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production

  # Configuration du service frontend
  - type: web
    name: smart-parking-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile.frontend
    rootDir: ./
    plan: free
    envVars:
      - key: API_URL
        fromService:
          name: smart-parking-api
          type: web
          property: host
