services:
  # Configuration du service backend
  - type: web
    name: smart-parking-api
    runtime: docker
    buildCommand: docker build -t smart-parking-api -f Dockerfile.backend .
    startCommand: docker run -p $PORT:5000 smart-parking-api
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production

  # Configuration du service frontend
  - type: web
    name: smart-parking-frontend
    runtime: docker
    buildCommand: cd frontend && docker build -t smart-parking-frontend -f Dockerfile.frontend .
    startCommand: docker run -p $PORT:80 -e API_URL=${API_URL} smart-parking-frontend
    plan: starter
    envVars:
      - key: API_URL
        fromService:
          name: smart-parking-api
          type: web
          property: url
